### ISSUE TITLE
nothing happens at all

### ISSUE THREAD

**Issue by pedrohaccorsi** [loic2665/HeartRateToWeb#12]
I'm trying both csharp and python options, but once the server starts nothing happens, data never reaches it.

these are the devices:

- win10 build 1909
- galaxy active 2
- galaxy s9

My steps are:

1. connect watch to smartphone via bluetooth
2. init server 
3. init app

But nothing happens... I have triple checked and the server endpoint shown by the PC app are exactly the same as the one entered in the watch.

any ideias?

**Comment by vyazikov** [comment]
hi.
Your smartphone  needs to be connected to the same  Wi-fi network as your PC. While your watch is connected to your phone via bluetooth.
also be sure, that windows Firewall is turned off. Samsung Watch 3 - working perfect.

**Comment by pedrohaccorsi** [comment]
I believe that my problem is the firewall step... I am using my business laptop which has admin config over firewall and ect, which I dont have access to. later today I'll try on a personal laptop and see what happens!

**Comment by vyazikov** [comment]
This works really easy, all is need to do, is put all devices inside the same network.
Also be sure, that you have needed python libraries installed and there is no errors wrile running python script.
works great)

**Comment by tsolom01** [comment]
Thanks for the information. Done all the steps still getting the verify server error. 
Also i get this error when i run it with python
![image](https://user-images.githubusercontent.com/55096615/115450350-7297b780-a224-11eb-8c72-64f61696e1ea.png)

**Comment by tsolom01** [comment]
> Thanks for the information. Done all the steps still getting the verify server error.
> Also i get this error when i run it with python
> ![image](https://user-images.githubusercontent.com/55096615/115450350-7297b780-a224-11eb-8c72-64f61696e1ea.png)

fix that, it works perfectly now, thanks for the help and thanks for the amazing work!!

**Comment by vyazikov** [comment]
yeap) just launch the script as Admin or manually create hr.txt file at the same dir

**Comment by loic2665** [comment]
Hello ! Sorry for the late answer, i had pretty busy days, yes, try to create a rule to allow the port 6547 with the app, (don't disable your firewall, it's a big security hole then...) for the python version, i'm surprised that it gives an error on the hr.txt file... you can create it but this is weird... I recommand you the cSharp version of this program. :)

**Comment by pedrohaccorsi** [comment]
I took my a while to get back! but I tried the py project in my personal machine and it worked fine, so I really believe that the problem is related to some firewall in my company machine. for me, this issue can be closed

**Comment by loic2665** [comment]
Hey ! Thanks for your feedback ! It's closed. ;)
