### ISSUE TITLE
Error on sending data (verify server)

### ISSUE THREAD

**Issue by tsolom01** [loic2665/HeartRateToWeb#13]
I tried with both releases and didnt find any luck. On the smart watch app i insert my IP http://192.168.10.etc:6547 like that and on the csharp executable i start that sever, it says it s on, and the watch app says that it sent data there but on the error says 'Error on sending data (verify server)'. 

Do i have to do anything else besides downloading the app and git? Should i connect with bluetooth my galaxy active 2 to my laptop?

**Comment by vyazikov** [comment]
hi there. please read the topic below, the same question is explained
