### ISSUE TITLE
Issue with compiling Tizen native app on Tizen studio after project import

### ISSUE THREAD

**Issue by F9Alejandro** [loic2665/HeartRateToWeb#8]
Tizen studio gives odd errors when trying to compile or even emulate the app. When importing it gives odd errors of not being able to load the xml file even though creating a new project and just moving it over works.

But doing the same for the rest of the project doesn't work and leaves issues with trying to emulate entirely.

**Comment by carlos-garcia** [comment]
Just had same issue, this repo doesnt commit tizen studio files.. i had to create a blank project, copy the tizen native app files there, and its working without issues.

**Comment by F9Alejandro** [comment]
Got it working. Thanks for the little tip :)
